package com.shaic.claim.selecthospital.ui;

import javax.inject.Inject;

import org.vaadin.addon.cdimvp.ViewComponent;
import org.vaadin.csvalidation.CSValidator;

import com.shaic.arch.EnhancedFieldGroupFieldFactory;
import com.shaic.claim.intimation.create.dto.HospitalDto;
import com.shaic.newcode.wizard.pages.IntimationDetailsPage;
import com.vaadin.cdi.UIScoped;
import com.vaadin.v7.data.fieldgroup.BeanFieldGroup;
import com.vaadin.server.ThemeResource;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.FormLayout;
import com.vaadin.v7.ui.HorizontalLayout;
import com.vaadin.ui.Panel;
import com.vaadin.v7.ui.TextField;
import com.vaadin.v7.ui.VerticalLayout;

@UIScoped
public class HospitalSearch extends ViewComponent {
	
	private static final long serialVersionUID = 1L;
	
	@Inject
	private IntimationDetailsPage intimationDetailsPage;

	private BeanFieldGroup<HospitalDto> binder;

	private TextField txtHospitalId;
	
	private TextField txtHospitalName;	
	
	private Button btnHospitalId;
	
	private Button btnHospitalName;
	

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	
	public void init() {
		VerticalLayout HospitalSearchLayout = buildHospitalSearchLayout();
		HospitalSearchLayout.setWidth("100%");
		HospitalSearchLayout.setHeight("100%");
		HospitalSearchLayout.setSpacing(true);
		HospitalSearchLayout.setMargin(true);
		Panel hospitalPanel = new Panel();
		hospitalPanel.setContent(HospitalSearchLayout);
		setCompositionRoot(hospitalPanel);
	}

	private VerticalLayout buildHospitalSearchLayout() {
		this.binder = new BeanFieldGroup<HospitalDto>(
				HospitalDto.class);
		binder.setFieldFactory(new EnhancedFieldGroupFieldFactory());
		
		txtHospitalId = binder.buildAndBind("Hospital Code", "hospitalCode",
				TextField.class);				
		btnHospitalId = new Button();
		btnHospitalId.setStyleName("link");
		btnHospitalId.setIcon(new ThemeResource("images/search.png"));
		txtHospitalId.setMaxLength(15);
		CSValidator validator = new CSValidator();
		validator.extend(txtHospitalId);
		validator.setRegExp("^[a-zA-Z0-9-]*$");
		validator.setPreventInvalidTyping(true);
		txtHospitalName = binder.buildAndBind("Hospital Name", "name",
				TextField.class);		
		btnHospitalName = new Button();		
		btnHospitalName.setStyleName("link");
		btnHospitalName.setIcon(new ThemeResource("images/search.png"));
		txtHospitalName.setMaxLength(100);
		/*validator = new CSValidator();
		validator.extend(txtHospitalName);
		validator.setRegExp("^[a-zA-Z ().-]*$");
		validator.setPreventInvalidTyping(true);*/
		HorizontalLayout searchByIdLayout = new HorizontalLayout(txtHospitalId,btnHospitalId);
		searchByIdLayout.setComponentAlignment(btnHospitalId, Alignment.BOTTOM_RIGHT);
		HorizontalLayout searchByNameLayout = new HorizontalLayout(txtHospitalName, btnHospitalName);
		searchByNameLayout.setComponentAlignment(btnHospitalName, Alignment.BOTTOM_RIGHT);
		HorizontalLayout searchFormLayout = new HorizontalLayout(new FormLayout(searchByIdLayout), new FormLayout(searchByNameLayout));
		searchFormLayout.setWidth("80%");
		addListener();
		return new VerticalLayout(searchFormLayout);
	}

	public void addListener() {
		btnHospitalId.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				txtHospitalName.setValue(null);
				HospitalDto hospitalDTO = new HospitalDto();
				hospitalDTO.setHospitalCode(txtHospitalId.getValue());
				if (hospitalDTO != null) {
					intimationDetailsPage.searchHospitalIdClick(hospitalDTO);
				}
			}
		});
		
		btnHospitalName.addClickListener(new Button.ClickListener() {
			private static final long serialVersionUID = 1L;

			@Override
			public void buttonClick(ClickEvent event) {
				txtHospitalId.setValue(null);
				HospitalDto hospitalDTO = new HospitalDto();
				hospitalDTO.setName(txtHospitalName.getValue());
				if (hospitalDTO != null) {
					intimationDetailsPage.searchHospitalNameClick(hospitalDTO);
				}
			}			
		});
	}
	
	public void resetHospitalId(){
		txtHospitalId.setValue(null);
	}
	
	public void resetHospitalName(){
		txtHospitalName.setValue(null);
	}

}