package com.shaic.claim.intimation;

import javax.ejb.EJB;

import com.shaic.arch.SHAUtils;
import com.shaic.domain.MasterService;
import com.shaic.domain.PolicyCondition;
import com.vaadin.annotations.AutoGenerated;
import com.vaadin.cdi.UIScoped;
import com.vaadin.v7.data.util.BeanItemContainer;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.Button.ClickListener;
import com.vaadin.ui.Panel;
import com.vaadin.v7.ui.Table;
import com.vaadin.v7.ui.VerticalLayout;
import com.vaadin.ui.Window;

@UIScoped
@SuppressWarnings("serial")
public class ViewConditions extends Window {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1536089516171582888L;
	private Panel intimationPanel;
	@AutoGenerated
	
	private VerticalLayout layout;
	
	@EJB
	private MasterService masterService;
	
	private Button btnClose;
	
	/**
	 * The constructor should first build the main layout, set the
	 * composition root and then do any custom initialization.
	 *
	 * The constructor will not be automatically regenerated by the
	 * visual editor.
	 */
	public ViewConditions(BeanItemContainer<PolicyCondition> policyConditionsBean) {
		
		  super("View Policy Conditions");
		  intimationPanel  = buildMainLayout(policyConditionsBean);
		  this.setWidth(900, Unit.PIXELS);
		  this.setHeight(600, Unit.PIXELS);
		  layout = new VerticalLayout();
		  layout.addComponent(intimationPanel);
		  btnClose = new Button("Close");
		  btnClose.setData(this);
		  listener();
		//  layout.addComponent(btnClose);
		  layout.setComponentAlignment(intimationPanel, Alignment.MIDDLE_CENTER);
		 // layout.setComponentAlignment(btnClose, Alignment.MIDDLE_CENTER);
		  setContent(layout);
		  setModal(true);
		  setClosable(true);
		  setResizable(false);
	}

	@AutoGenerated
	private Panel buildMainLayout(BeanItemContainer<PolicyCondition> policyConditionsBean) {
		
		// intimationPanel
		intimationPanel = new Panel("Policy Conditions");
		
		Table policyConditionsTable =  new Table();
		policyConditionsTable.addStyleName("tableheight");
		policyConditionsTable.setContainerDataSource(policyConditionsBean);
		
		Object[] columns = new Object[]{"description", "productRules"};
		policyConditionsTable.setVisibleColumns(columns);
		
		policyConditionsTable.setColumnHeader("description", "Short Description");
		policyConditionsTable.setColumnHeader("productRules", "Long Description");
		policyConditionsTable.setColumnExpandRatio("productRules", SHAUtils.getFloatFromString("2.00"));
//		policyConditionsTable.setWidth(900, Unit.PIXELS);
//		policyConditionsTable.setHeight(500, Unit.PIXELS);
		policyConditionsTable.setSizeFull();
		policyConditionsTable.setPageLength(policyConditionsTable.size());
		intimationPanel.setContent(policyConditionsTable);
		
		return intimationPanel;
	}
	private void listener(){
		btnClose.addClickListener(new ClickListener() {
			
			@Override
			public void buttonClick(ClickEvent event) {
				Window w = (Window) btnClose.getData();
				w.setClosable(true);
				
			}
		});
		
	}

}
