var CustomStyle=(function CustomStyleClosure(){var prefixes=['ms','Moz','Webkit','O'];var _cache={};function CustomStyle(){}
CustomStyle.getProp=function get(propName,element){if(arguments.length==1&&typeof _cache[propName]=='string'){return _cache[propName]}
element=element||document.documentElement;var style=element.style,prefixed,uPropName;if(typeof style[propName]=='string'){return(_cache[propName]=propName)}
uPropName=propName.charAt(0).toUpperCase()+propName.slice(1);for(var i=0,l=prefixes.length;i<l;i++){prefixed=prefixes[i]+uPropName;if(typeof style[prefixed]=='string'){return(_cache[propName]=prefixed)}}
return(_cache[propName]='undefined')};CustomStyle.setProp=function set(propName,element,str){var prop=this.getProp(propName);if(prop!='undefined')
element.style[prop]=str};return CustomStyle})();var TextLayerBuilder=function textLayerBuilder(textLayerDiv,pageIdx){var textLayerFrag=document.createDocumentFragment();this.textLayerDiv=textLayerDiv;this.layoutDone=!1;this.divContentDone=!1;this.pageIdx=pageIdx;this.matches=[];this.beginLayout=function textLayerBuilderBeginLayout(){this.textDivs=[];this.renderingDone=!1};this.endLayout=function textLayerBuilderEndLayout(){this.layoutDone=!0;this.insertDivContent()};this.renderLayer=function textLayerBuilderRenderLayer(){var textDivs=this.textDivs;var bidiTexts=this.textContent.bidiTexts;var textLayerDiv=this.textLayerDiv;var canvas=document.createElement('canvas');var ctx=canvas.getContext('2d');var MAX_TEXT_DIVS_TO_RENDER=100000;if(textDivs.length>MAX_TEXT_DIVS_TO_RENDER)
return;for(var i=0,ii=textDivs.length;i<ii;i++){var textDiv=textDivs[i];if('isWhitespace' in textDiv.dataset){continue}
textLayerFrag.appendChild(textDiv);ctx.font=textDiv.style.fontSize+' '+textDiv.style.fontFamily;var width=ctx.measureText(textDiv.textContent).width;if(width>0){var textScale=textDiv.dataset.canvasWidth/width;var transform='scale('+textScale+', 1)';if(bidiTexts[i].dir==='ttb'){transform='rotate(90deg) '+transform}
CustomStyle.setProp('transform',textDiv,transform);CustomStyle.setProp('transformOrigin',textDiv,'0% 0%');textLayerDiv.appendChild(textDiv)}}
this.renderingDone=!0;textLayerDiv.appendChild(textLayerFrag)};this.setupRenderLayoutTimer=function textLayerSetupRenderLayoutTimer(){var RENDER_DELAY=200;var self=this;if(Date.now()-0>RENDER_DELAY){this.renderLayer()}else{if(this.renderTimer)
clearTimeout(this.renderTimer);this.renderTimer=setTimeout(function(){self.setupRenderLayoutTimer()},RENDER_DELAY)}};this.appendText=function textLayerBuilderAppendText(geom){var textDiv=document.createElement('div');var fontHeight=geom.fontSize*Math.abs(geom.vScale);textDiv.dataset.canvasWidth=geom.canvasWidth*geom.hScale;textDiv.dataset.fontName=geom.fontName;textDiv.style.fontSize=fontHeight+'px';textDiv.style.fontFamily=geom.fontFamily;textDiv.style.left=geom.x+'px';textDiv.style.top=(geom.y-fontHeight)+'px';this.textDivs.push(textDiv)};this.insertDivContent=function textLayerUpdateTextContent(){if(!this.layoutDone||this.divContentDone||!this.textContent)
return;this.divContentDone=!0;var textDivs=this.textDivs;var bidiTexts=this.textContent.bidiTexts;for(var i=0;i<bidiTexts.length;i++){var bidiText=bidiTexts[i];var textDiv=textDivs[i];if(!/\S/.test(bidiText.str)){textDiv.dataset.isWhitespace=!0;continue}
textDiv.textContent=bidiText.str;textDiv.dir=bidiText.dir==='rtl'?'rtl':'ltr'}
this.setupRenderLayoutTimer()};this.setTextContent=function textLayerBuilderSetTextContent(textContent){this.textContent=textContent;this.insertDivContent()}};function getOutputScale(){var pixelRatio='devicePixelRatio' in window?window.devicePixelRatio:1;return{sx:pixelRatio,sy:pixelRatio,scaled:pixelRatio!=1}}